---
default_stages: [commit, push]
default_language_version:
  python: python3
minimum_pre_commit_version: "1.20.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-encoding-pragma
        args:
          - --remove
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: insert-license
        name: Add license to all executable files
        exclude: ^\.github/.*$
        args:
          - --comment-style
          - "|#|"
          - --license-filepath
          - LICENSE
          - --fuzzy-match-generates-todo
        files: >
          \.sh$|\.bash$|\.py$|\.yml$|\.yaml$
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    - id: black
      name: Black
      types: [python]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        name: Run isort to sort imports
        args: ['--multi-line', '3', '--trailing-comma']
        files: \.py$
